#![allow(dead_code)]

use std::fs;
use std::os::unix::fs::{symlink, PermissionsExt};
use std::path::{Path, PathBuf};
use std::process::Command;

fn hard_link_tree(source: &Path, destination: &Path) {
    fs::create_dir_all(destination).unwrap();
    for entry in fs::read_dir(source).unwrap() {
        let entry = entry.unwrap();
        let source_path = entry.path();
        let destination_path = destination.join(entry.file_name());
        let file_type = entry.file_type().unwrap();
        if file_type.is_dir() {
            hard_link_tree(&source_path, &destination_path);
        } else if file_type.is_symlink() {
            symlink(fs::read_link(&source_path).unwrap(), &destination_path).unwrap();
        } else {
            fs::hard_link(&source_path, &destination_path).unwrap();
        }
    }
}

pub fn materialize_real_host_toolchain(repository: &Path) -> String {
    let cargo = Command::new("rustup")
        .args(["which", "cargo"])
        .output()
        .unwrap();
    assert!(cargo.status.success());
    let cargo = PathBuf::from(String::from_utf8(cargo.stdout).unwrap().trim());
    let rustc = Command::new("rustup")
        .args(["which", "rustc"])
        .output()
        .unwrap();
    assert!(rustc.status.success());
    let rustc = PathBuf::from(String::from_utf8(rustc.stdout).unwrap().trim());
    let toolchain_root = cargo.parent().unwrap().parent().unwrap();
    assert_eq!(rustc.parent().unwrap().parent().unwrap(), toolchain_root);

    let guest_toolchain = repository.join("host-toolchain");
    let guest_bin = guest_toolchain.join("bin");
    fs::create_dir_all(&guest_bin).unwrap();
    fs::hard_link(&cargo, guest_bin.join("cargo")).unwrap();
    fs::hard_link(&rustc, guest_bin.join("rustc")).unwrap();
    hard_link_tree(&toolchain_root.join("lib"), &guest_toolchain.join("lib"));

    fs::create_dir_all(repository.join("src")).unwrap();
    fs::create_dir_all(repository.join(".cargo")).unwrap();
    fs::write(
        repository.join("Cargo.toml"),
        "[package]\nname = \"forge-toolchain-smoke\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[lib]\ndoctest = false\n",
    )
    .unwrap();
    fs::write(
        repository.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"forge-toolchain-smoke\"\nversion = \"0.1.0\"\n",
    )
    .unwrap();
    fs::write(
        repository.join("src/lib.rs"),
        r##"#[cfg(test)]
mod tests {
    #[test]
    fn authorized_toolchain_executes_tests() {
        println!(
            "{}",
            r#"FORGE_GATE_EVIDENCE:{"schema_version":"forge.mission.gate_evidence_observation.v1","evidence":{"requirements_summary":"Repository requirements were inspected.","acceptance_criteria":["The authorized host toolchain executes inside the sandbox."],"structured_delivery":{"status":"completed","summary":"The bounded delivery passed the real toolchain smoke."},"no_unresolved_risks":true,"security_attestation":"The isolated security checks passed.","release_manifest":"The release manifest is complete."}}"#
        );
        assert_eq!(2 + 2, 4);
    }
}
"##,
    )
    .unwrap();
    fs::write(
        repository.join(".cargo/config.toml"),
        "[build]\nrustc = \"/workspace/host-toolchain/bin/rustc\"\ntarget-dir = \"/tmp/forge-target\"\nrustflags = [\"-C\", \"linker=/usr/bin/cc\"]\n",
    )
    .unwrap();
    guest_bin.join("cargo").to_str().unwrap().to_string()
}

pub fn write_gate_evidence_command(repository: &Path) -> String {
    let command = repository.join("fixture-bin/git");
    fs::create_dir_all(command.parent().unwrap()).unwrap();
    fs::write(
        &command,
        "#!/bin/sh\nprintf '%s%s\\n' 'FORGE_GATE_EVIDENCE:' \"${1:?missing evidence envelope}\"\n",
    )
    .unwrap();
    fs::set_permissions(&command, fs::Permissions::from_mode(0o755)).unwrap();
    command.to_str().unwrap().to_string()
}

pub fn gate_evidence_envelope(evidence: &[&str]) -> String {
    let mut values = serde_json::Map::new();
    for kind in evidence {
        let value = match *kind {
            "requirements_summary" => {
                serde_json::json!("Repository requirements were inspected and summarized.")
            }
            "acceptance_criteria" => serde_json::json!([
                "The requested behavior is exercised by an isolated operational smoke."
            ]),
            "structured_delivery" => serde_json::json!({
                "status": "completed",
                "summary": "The bounded delivery passed its authorized checks."
            }),
            "no_unresolved_risks" => serde_json::json!(true),
            "review_passed" => continue,
            other => serde_json::json!({"observed": other}),
        };
        values.insert((*kind).to_string(), value);
    }
    serde_json::json!({
        "schema_version": "forge.mission.gate_evidence_observation.v1",
        "evidence": values,
    })
    .to_string()
}
